### ISSUE TITLE
Change to flexible size data in I2C

### ISSUE THREAD

**Issue by burger1473** [spacebee-technologies/udp-bridge#7]

**Comment by Sanntin** [comment]
## Problem
El master cuando lee en el slave necesita saber los bytes del mensaje que esta esperando. Solo estaria leyendo instrucciones. **[Hay algo mas??]**

El master cuando escribe manda los bytes que tiene, no hay problema con el largo del mensaje (revisar que el buffer del slave no se llene).

## Approaches:

### Fixed data send 
Por I2C siempre se envia el mismo largo de mensaje, con la longitud del mensaje mas largo posible. Y despúes se recorta en el MCU la información útil. 

### Conocer largo de mensaje
Siempre que el MCU lee un mensaje de I2C, realiza dos lecturas, la primera para obtener el largo del mensaje, y la segunda para leer el mensaje.

- Guardar en una cola el largo de todos los mensajes almacenados en la cola de mensajes.
- Guardar en un atributo de la cola, la longitud del valor del primer mensaje en la cola.

**Comment by Sanntin** [comment]
⚠️ Warning ⚠️ 
Cuando se remplaza un mensaje en la cola, hay que tener cuidado que no tenga datos residuales.
